spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/otrack?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

server.port: 8081

logging.file: track.log